### ISSUE TITLE
arm64 image?

### ISSUE THREAD

**Issue by dkrizic** [enix/dothill-csi#101]
Would it be possible to provide the image

```
enix/san-iscsi-csi
```

as a multi arch image covering

* amd64 (as now)
* arm64 (additionally)

Background: I have a hybrid cluster with amd64 and arm64 nodes and the daemonset does not run on arm64 nodes.

**Comment by rdegez** [comment]
Hi,

This project has been superseded by https://github.com/Seagate/seagate-exos-x-csi.

May I suggest you re-open this issue there ? :-)

Cheers
