### ISSUE TITLE
Dell PowerVault ME4

### ISSUE THREAD

**Issue by sysmso** [enix/dothill-csi#102]
Hi there !

I am using Dell Powervault ME4024 disk storage which is claimed to be supported, I try to use the driver but I encounter an authentication problem to the API. 

Controller logs : 
```
I1103 14:36:37.346453 1 driver.go:112] === [ROUTINE START] /csi.v1.Controller/CreateVolume ===
I1103 14:36:37.346501 1 controller.go:243] using dothill API at address https://sanip/api
I1103 14:36:37.346513 1 controller.go:245] dothill client is already configured for this API, skipping login
I1103 14:36:37.346528 1 provisioner.go:67] received 5368709120B volume request
I1103 14:36:37.346539 1 provisioner.go:76] creating volume fde4b27e9ae44ddd9750fd92c4368b17 (size 5368709120B) in pool A
I1103 14:36:37.346568 1 dothill.go:94] -> GET /login/<hidden>
I1103 14:36:37.719588 1 dothill.go:124] <- [2 Error] <hidden>
E1103 14:36:37.719723 1 driver.go:118] Dothill API returned non-zero code 2 (Invalid sessionkey)
I1103 14:36:37.719737 1 driver.go:121] === [ROUTINE END] /csi.v1.Controller/CreateVolume === 
```

Kubernetes version : 1.24.4

API documentation : https://www.dell.com/support/manuals/fr-fr/powervault-me4024/me4_series_cli_pub/using-a-script-to-access-the-cli?guid=guid-9ae5ccd6-a207-42df-b2f3-1e02a487a354&lang=en-us

Can you help me?

Thanks !

**Comment by lcaflc** [comment]
This project is no longer maintained. I invite you to check [seagate-exos-x-csi](https://github.com/Seagate/seagate-exos-x-csi)
