### ISSUE TITLE
[2.4.1] error while trying to resize

### ISSUE THREAD

**Issue by abuisine** [enix/dothill-csi#83]
While resizing using the 2.4.1, I get an error message both as a `warning` event on the PVC and as a log line in the controller
![Screenshot 2021-02-18 at 13 46 13](https://user-images.githubusercontent.com/1078681/108395784-72743f00-7216-11eb-98cf-f4a8ea0e2d73.png)
![Screenshot 2021-02-18 at 13 44 21](https://user-images.githubusercontent.com/1078681/108395818-7902b680-7216-11eb-9fcc-5553651d4086.png)

**Comment by plaffitt** [comment]
The "**unsupported protocol scheme**" error comes from the fact that `csi.storage.k8s.io/controller-expand-secret-name` and `csi.storage.k8s.io/controller-expand-secret-namespace` storage class' parameters are missing. Thus, the client is not configured and the server address is missing, including the `https://` part, which cause the error.

I've added a check before executing api calls and a section in the FAQ about this issue and how to handle it.
