### ISSUE TITLE
add artifacthub.io annotations on helm chart

### ISSUE THREAD

**Issue by abuisine** [enix/dothill-csi#85]
We should enable security scan on the container throught the addition of the following helm chart annotations :  
```
artifacthub.io/images: |
    - name: dothill-csi
      image: enix/dothill-csi:vX.Y.Z
```
reference here : https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations

**Comment by plaffitt** [comment]
closed by dd7dca7a1e74be47750cdf5f870e90adc8073253
