### ISSUE TITLE
iscsid & multipathd should rather be hosted outside of the dothill plugin

### ISSUE THREAD

**Issue by abuisine** [enix/dothill-csi#88]
`iscsid` & `multipathd` are today within sidecars in order for the dothill-csi plugin to monitor the status.
Although a lot of reasons pushed into the project in this direction, it seems clear that it creates problems and makes it very difficult to support various linux distribution (debian, ubuntu, centos, rancheros, ...).

Another option should be considered.

**Comment by plaffitt** [comment]
closed by df4267223f19d1a7367347e75fd602c56c599420
